### ISSUE TITLE
Make adjustments for running in browser

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#1]
### Subtasks to accomplish
- [x] Optimize dependencies and load times #11
- [x] Setup bundle size limits CI #10
- [x] Optimise css bundles #87
