### ISSUE TITLE
Implement breakpoints of menu

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#109]
This was split into subtasks
- [x] Implement the off-canvas menu for S breakpoint #125
- [x] Implement the off-canvas menu for L breakpoint #126
- [x] Finalize main menu redesign #147
