### ISSUE TITLE
Display the list of top accounts

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2454]
### Description
As a user I'd like to see the list of accounts with the most tokens in Lisk Hub. I'd like to know what percentage of the total LSK supply they hold.

Design: https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/386073386_Discovery_-_Top_Accounts

Acceptance Criteria

- [ ] Page should  loaded with top 30 accounts initially .
- [ ] Selecting "more" button should add next 30 top accounts (as per our standard) with the existing list and this step continues 
- [ ] Clicking a row should lead to detail page of given account
- [ ] The page should match with the proposed design. Refer inVision.
