### ISSUE TITLE
Display graphical statistics of blocks

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2458]
### Summary
As an advanced user; I'd like to a summary of key specifications of the blocks on the blockchain, such as:
- Number of transactions per block.
- Last full block. ( Not sure )
- Distribution of transaction types.
- The proportion of empty blocks.
Graphs can help illustrate the concept.

Design : https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/385615580_Governance_-_Blocks_-Stats_And_Blocks-
Note: The above design is not approved by PO yet.

Acceptance Criteria

- [ ] User should see the last 10, 50 and 101 blocks transaction details in a graphical format
- [ ] The graph should have legends
- [ ] The graph should have tool tip when user rollover on it
- [ ] The page should display the last 10 blocks transaction details by default
- [ ] The design should match the proposed design available in inVision
