### ISSUE TITLE
Support Lisk Core v3.0

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#2732]
### Description
Getting closer to the release of Lisk Core v3.0, we need to prepare Lisk Desktop to work with this version as well as Lisk Core v2.x.

List of the changes:
- [x] Map send transaction `recipientId` and `amount` from `asset`
- [x] Map transaction `asset.delegate` to `asset`
- [x] Map delegate `vote` to `voteWeight`
- [x] Compute `rank` for all delegates on startup
- [x] Fix delegates sort since `rank` is no longer available
- [x] Recompute `rank`s when `approval`s change at the end of each round
- [x] Map new peer.state values to old ones.
- [x] Changes required to sign a transactions. [Here](https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-transactions/src/transfer.ts#L28-L37) are the new properties.

### Action points
- Import Lisk Element version 2.3.1 and 3.0.0 in the package.
- Detect the beta net and choose the correct Lisk Element to interact with the core API.
- Adapt the representational component according to the API version.

### Acceptance criteria
- The transactions list should show all the information as before.
- The transaction details page should list of the details of all transactions types correctly.
- Voting functionality should work.
- Delegate registration should work.
- Second passphrase registration should work.
- Delegate monitor section should show the all delegate information - including forging time and status - correctly.
- Sending LSK to other accounts should work with and without message.
