### ISSUE TITLE
Fix bugs caused by refactoring the API utility

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-desktop#3209]
After refactoring the API utility according to #2890, the following issues have been discovered which are caused by differences between the current and the previous implementation of the API utility:

- [ ] The `AccountInfo` components accepts `netCode` to pass to `validateAddress`. But the said function now accepts `network` from the Redux store. #3221

- [ ] There's only one module left in `/utils/transactions` that can be moved to `/utils/api/transactions/lsk`. #3221

- [ ] Import statements have outdated paths. #3221

**Comment by reyraa** [comment]
Resolved by #3221.
