### ISSUE TITLE
Prepare Lisk Desktop v3.0.0 for rc

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#4363]
### Description

The purpose of this epic is to prepare the Lisk Desktop v3.0.0-rc.0 release

### Tasks

- [x] LiskHQ/lisk-desktop#4757 
- [x] LiskHQ/lisk-desktop#4992 
- [x] LiskHQ/lisk-desktop#5003 
- [x] LiskHQ/lisk-desktop#5007
- [x] LiskHQ/lisk-desktop#5008
- [x] LiskHQ/lisk-desktop#5009 
- [x] LiskHQ/lisk-desktop#2189
- [x] LiskHQ/lisk-desktop#4983
- [x] LiskHQ/lisk-desktop#4971 
- [x] LiskHQ/lisk-desktop#4509 
- [x] LiskHQ/lisk-desktop#5005
- [x] LiskHQ/lisk-desktop#4984
- [x] LiskHQ/lisk-desktop#4522
- [x] LiskHQ/lisk-desktop#5010
- [x] LiskHQ/lisk-desktop#5006
- [x] LiskHQ/lisk-desktop#4698
- [x] LiskHQ/lisk-desktop#5025
- [x] LiskHQ/lisk-desktop#5023
- [x] LiskHQ/lisk-desktop#5022
- [x] LiskHQ/lisk-desktop#5020
- [x] LiskHQ/lisk-desktop#5019
- [x] LiskHQ/lisk-desktop#5021
- [x] LiskHQ/lisk-desktop#5024
- [x] LiskHQ/lisk-desktop#5015 
- [x] LiskHQ/lisk-desktop#5049 
- [x] LiskHQ/lisk-desktop#5045
- [x] LiskHQ/lisk-desktop#5044
- [x] LiskHQ/lisk-desktop#5042
- [x] LiskHQ/lisk-desktop#5039
- [x] LiskHQ/lisk-desktop#5035 
- [x] LiskHQ/lisk-desktop#5047
- [x] LiskHQ/lisk-desktop#5036
- [x] LiskHQ/lisk-desktop#5034 
- [x] LiskHQ/lisk-desktop#5032
- [x] LiskHQ/lisk-desktop#5029
- [x] LiskHQ/lisk-desktop#5016 
- [x] LiskHQ/lisk-desktop#5043
- [x] LiskHQ/lisk-desktop#5018
- [x] LiskHQ/lisk-desktop#5037
- [x] LiskHQ/lisk-desktop#5077
- [x] LiskHQ/lisk-desktop#5090
- [x] LiskHQ/lisk-desktop#5048
- [x] LiskHQ/lisk-desktop#5067
- [x] LiskHQ/lisk-desktop#5069
- [x] LiskHQ/lisk-desktop#5075
- [x] LiskHQ/lisk-desktop#5041
- [x] LiskHQ/lisk-desktop#5098
- [x] LiskHQ/lisk-desktop#5040
- [x] LiskHQ/lisk-desktop#4987
- [x] LiskHQ/lisk-desktop#5031 
- [x] LiskHQ/lisk-desktop#5026
- [x] LiskHQ/lisk-desktop#5027
- [x] LiskHQ/lisk-desktop#4674
- [x] LiskHQ/lisk-desktop#5064
- [x] LiskHQ/lisk-desktop#5068
- [x] LiskHQ/lisk-desktop#5074
- [x] LiskHQ/lisk-desktop#5122
- [x] LiskHQ/lisk-desktop#5124
- [x] LiskHQ/lisk-desktop#5100
- [x] LiskHQ/lisk-desktop#5103
- [x] LiskHQ/lisk-desktop#5131
- [x] LiskHQ/lisk-desktop#5130
- [x] LiskHQ/lisk-desktop#5129
- [x] LiskHQ/lisk-desktop#5109
- [x] LiskHQ/lisk-desktop#4663
- [x] LiskHQ/lisk-desktop#3985 
- [x] LiskHQ/lisk-desktop#4575
- [x] LiskHQ/lisk-desktop#5116
- [x] LiskHQ/lisk-desktop#5057
- [x] LiskHQ/lisk-desktop#5128
- [x] LiskHQ/lisk-desktop#5118
- [x] LiskHQ/lisk-desktop#5115
- [x] LiskHQ/lisk-desktop#5113
- [x] LiskHQ/lisk-desktop#5114
- [x] LiskHQ/lisk-desktop#5111
- [x] LiskHQ/lisk-desktop#5112
- [x] LiskHQ/lisk-desktop#5142
- [x] LiskHQ/lisk-desktop#5139
- [x] LiskHQ/lisk-desktop#5138
- [x] LiskHQ/lisk-desktop#5137
- [x] LiskHQ/lisk-desktop#5117
- [x] LiskHQ/lisk-desktop#5136
- [x] LiskHQ/lisk-desktop#5132
- [x] LiskHQ/lisk-desktop#5134
- [x] LiskHQ/lisk-desktop#5150
- [x] LiskHQ/lisk-desktop#5164
- [x] LiskHQ/lisk-desktop#5165
- [x] LiskHQ/lisk-desktop#5163
- [x] LiskHQ/lisk-desktop#5166
- [x] LiskHQ/lisk-desktop#5160
- [x] LiskHQ/lisk-desktop#5055
- [x] LiskHQ/lisk-desktop#5096
- [x] LiskHQ/lisk-desktop#5143
- [x] LiskHQ/lisk-desktop#5141
- [x] LiskHQ/lisk-desktop#5177
- [x] LiskHQ/lisk-desktop#5140
- [x] LiskHQ/lisk-desktop#5102
- [x] LiskHQ/lisk-desktop#5107
- [x] LiskHQ/lisk-desktop#5192
- [x] LiskHQ/lisk-desktop#5188
- [x] LiskHQ/lisk-desktop#5191
- [x] LiskHQ/lisk-desktop#5193
- [x] LiskHQ/lisk-desktop#5194
- [x] LiskHQ/lisk-desktop#5197
- [x] LiskHQ/lisk-desktop#5182
- [x] LiskHQ/lisk-desktop#5186
- [x] LiskHQ/lisk-desktop#4999 
- [x] LiskHQ/lisk-desktop#4989
- [x] LiskHQ/lisk-desktop#5110
- [x] LiskHQ/lisk-desktop#5189
- [x] LiskHQ/lisk-desktop#5184
- [x] LiskHQ/lisk-desktop#5190
- [x] LiskHQ/lisk-desktop#5195
- [x] LiskHQ/lisk-desktop#5126
- [x] LiskHQ/lisk-desktop#5215
- [x] LiskHQ/lisk-desktop#5240
- [x] LiskHQ/lisk-desktop#5228
- [x] LiskHQ/lisk-desktop#5223
- [x] LiskHQ/lisk-desktop#5217
- [x] LiskHQ/lisk-desktop#5244
- [x] LiskHQ/lisk-desktop#5242
- [x] LiskHQ/lisk-desktop#5210
- [x] LiskHQ/lisk-desktop#5235
- [x] LiskHQ/lisk-desktop#5236 
- [x] LiskHQ/lisk-desktop#5234 
- [x] LiskHQ/lisk-desktop#5227 
- [x] LiskHQ/lisk-desktop#5229
- [x] LiskHQ/lisk-desktop#5264
- [x] LiskHQ/lisk-desktop#5261
- [x] LiskHQ/lisk-desktop#5257
- [x] LiskHQ/lisk-desktop#5256
- [x] LiskHQ/lisk-desktop#5255
- [x] LiskHQ/lisk-desktop#5251
- [x] LiskHQ/lisk-desktop#5238
- [x] LiskHQ/lisk-desktop#5204
- [x] LiskHQ/lisk-desktop#5232 
- [x] LiskHQ/lisk-desktop#5230 
- [x] LiskHQ/lisk-desktop#5225 
- [x] LiskHQ/lisk-desktop#5218
- [x] LiskHQ/lisk-desktop#5237
- [x] LiskHQ/lisk-desktop#5254
- [x] LiskHQ/lisk-desktop#5266
- [x] LiskHQ/lisk-desktop#5270
- [x] LiskHQ/lisk-desktop#5273
- [x] LiskHQ/lisk-desktop#5278
- [x] LiskHQ/lisk-desktop#5279
- [x] LiskHQ/lisk-desktop#5283
- [x] LiskHQ/lisk-desktop#5284
- [x] LiskHQ/lisk-desktop#5293
- [x] LiskHQ/lisk-desktop#5295
- [x] LiskHQ/lisk-desktop#5299
- [x] LiskHQ/lisk-desktop#5301
- [x] LiskHQ/lisk-desktop#5303
- [x] LiskHQ/lisk-desktop#5305
- [x] LiskHQ/lisk-desktop#5304
