### ISSUE TITLE
Prepare Lisk Desktop v3.0.0 for production

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-desktop#4366]
### Description

The purpose of this epic is to prepare the Lisk Desktop v3.0.0 release

### Tasks

- [x] LiskHQ/lisk-desktop#5285
- [x] LiskHQ/lisk-desktop#5241
- [x] LiskHQ/lisk-desktop#5080
- [x] LiskHQ/lisk-desktop#5332
- [x] LiskHQ/lisk-desktop#5327
- [x] LiskHQ/lisk-desktop#5326
- [x] LiskHQ/lisk-desktop#5323
- [x] LiskHQ/lisk-desktop#5322
- [x] LiskHQ/lisk-desktop#5321
- [x] LiskHQ/lisk-desktop#5320
- [x] LiskHQ/lisk-desktop#5319
- [x] LiskHQ/lisk-desktop#5312
- [x] LiskHQ/lisk-desktop#5310
- [x] LiskHQ/lisk-desktop#5309
- [x] LiskHQ/lisk-desktop#5179
- [x] LiskHQ/lisk-desktop#5083
- [x] LiskHQ/lisk-desktop#5082
- [x] LiskHQ/lisk-desktop#5343
- [x] LiskHQ/lisk-desktop#5349
- [x] LiskHQ/lisk-desktop#5347
- [x] LiskHQ/lisk-desktop#5341
- [x] LiskHQ/lisk-desktop#5352
- [x] LiskHQ/lisk-desktop#5354
- [x] LiskHQ/lisk-desktop#5336
- [x] LiskHQ/lisk-desktop#5346
- [x] LiskHQ/lisk-desktop#5363
- [x] LiskHQ/lisk-desktop#5340
- [x] LiskHQ/lisk-desktop#5353
- [x] LiskHQ/lisk-desktop#5388
- [x] LiskHQ/lisk-desktop#5385
- [x] LiskHQ/lisk-desktop#5384
- [x] LiskHQ/lisk-desktop#5383 
- [x] LiskHQ/lisk-desktop#5380
- [x] LiskHQ/lisk-desktop#5378
- [x] LiskHQ/lisk-desktop#5377
- [x] LiskHQ/lisk-desktop#5374
- [x] LiskHQ/lisk-desktop#5373
- [x] LiskHQ/lisk-desktop#5372
- [x] LiskHQ/lisk-desktop#5386
- [x] LiskHQ/lisk-desktop#5173
- [x] LiskHQ/lisk-desktop#5317
- [x] LiskHQ/lisk-desktop#5306
- [x] LiskHQ/lisk-desktop#5357
- [x] LiskHQ/lisk-desktop#5400
- [x] LiskHQ/lisk-desktop#5371
- [x] LiskHQ/lisk-desktop#5348
- [x] LiskHQ/lisk-desktop#5393
- [x] LiskHQ/lisk-desktop#5411
- [x] LiskHQ/lisk-desktop#5412 
- [x] LiskHQ/lisk-desktop#5406
- [x] LiskHQ/lisk-desktop#4763
- [x] LiskHQ/lisk-desktop#4701
- [x] LiskHQ/lisk-desktop#5081
- [x] LiskHQ/lisk-desktop#5277
- [x] LiskHQ/lisk-desktop#5398
- [x] LiskHQ/lisk-desktop#5399
- [x] #5450
- [x] #5449
- [x] #5448
- [x] #5444
- [x] #5445
- [x] #5442
- [x] #5440
- [x] #5436
- [x] #5435
- [x] #5429
- [x] #5439 
- [x] #5428
- [x] #5434 
- [x] LiskHQ/lisk-desktop#5344
- [x] #5425
- [x] #5419
- [x] #5418
- [x] #5426
- [x] #5427
- [x] LiskHQ/lisk-desktop#5415
- [x] #5470
- [x] #5469
- [x] #5468
- [x] #5467
- [x] #5447
- [x] #5446
- [x] #5495
- [x] #5493
- [x] #5489
- [x] #5488
- [x] #5487
- [x] #5485
- [x] #5484
- [x] #5483
- [x] #5481
- [x] #5472
- [x] #5471
