### ISSUE TITLE
Implement the dashboard

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#59]
This should be tackled in the following subtasks:
- [x] Implement layout and latest activity of dashboard #131
- [x] Implement basic currency graph for dashboard #132
- [x] Implement advanced features of currency graph for dashboard #133
