### ISSUE TITLE
Implement search for accounts, transactions

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#64]
### Expected behaviour
https://drive.google.com/drive/u/2/folders/1DCjJ15LFRAaAjvo5D1cBBLNsxU3ujS03

These parts should be implemented:

- [x] Search landing page #247
- [x] Search result: LiskID #176
- [x] TransactionID detail page #246
- [x] Recent searches saved in localStorage #245
- [x] Implement XS breakpoint of search #263
- [x] Implement empty search result page #269
