### ISSUE TITLE
Implement redesign of voting

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#66]
Will be done in these parts:
- [x] Implement redesign of delegate list view #155
- [x] Implement redesign of delegate vote dialog #156
- [x] Implement filters of delegate list #215
- [x] Implement S breakpoint of delegates list #216
- [x] Implement S breakpoint of voting #217
