### ISSUE TITLE
Implement redesign of create new account component

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-desktop#7]
This should be done in these parts:
- [x] Create multistep component #12
- [x] Implement redesign of create step of get account #20
- [x] Implement redesign of safekeeping step of get account #19
- [x] Implement redesign of confirm step of get account #18
